// 兜底用的模拟数据：字段跟真实接口（backend /api/market 里的 news 数组）完全对齐。
// newsSource.js 会优先去拉真实数据，只有拉取失败（比如 Python 后端没启动）时才退回用这份。
export const mockNewsData = [
  {
    ago: "1 天前",
    kind: "市场",
    published: "2026-09-09T14:34:01+00:00",
    source: "Yahoo Personal Finance",
    summary: "",
    title: "什么是\"Lean FIRE\"运动? 它如何帮助您实现财务独立?",
    title_en: "What is the 'Lean FIRE' movement, and how can it help you reach financial independence?",
    url: "https://finance.yahoo.com/news/lean-fire-movement",
  },
  {
    ago: "2 小时前",
    kind: "公司",
    published: "2026-09-11T00:12:00+00:00",
    source: "Reuters",
    summary: "英伟达公布新一代AI芯片路线图，市场反应积极。",
    title: "英伟达公布下一代AI芯片路线图",
    title_en: "Nvidia unveils next-generation AI chip roadmap",
    url: "https://www.reuters.com/technology/nvidia-roadmap",
  },
  {
    ago: "5 小时前",
    kind: "市场",
    published: "2026-09-10T21:00:00+00:00",
    source: "Bloomberg",
    summary: "",
    title: "美联储9月议息会议临近，市场押注降息25个基点",
    title_en: "Fed rate decision looms as markets bet on 25bp cut",
    url: "https://www.bloomberg.com/news/fed-september-meeting",
  },
  {
    ago: "8 小时前",
    kind: "公司",
    published: "2026-09-10T18:20:00+00:00",
    source: "CNBC",
    summary: "特斯拉Q3交付数据超预期，股价盘后上涨。",
    title: "特斯拉Q3交付量超预期",
    title_en: "Tesla Q3 deliveries beat estimates",
    url: "https://www.cnbc.com/tesla-q3-deliveries",
  },
  {
    ago: "12 小时前",
    kind: "市场",
    published: "2026-09-10T14:00:00+00:00",
    source: "MarketWatch",
    summary: "",
    title: "半导体板块领涨，AI需求持续推高芯片股",
    title_en: "Semiconductor stocks lead rally on continued AI demand",
    url: "https://www.marketwatch.com/semiconductor-rally",
  },
];
