"""菜单 + 按钮权限码。admin 默认拥有全部；普通用户由管理员勾选。"""

from __future__ import annotations

# 菜单：侧栏可见
MENU_PERMS = [
    {"code": "menu.board", "label": "看板", "group": "菜单"},
    {"code": "menu.plans", "label": "计划", "group": "菜单"},
    {"code": "menu.dayPlan", "label": "计划 · 日计划", "group": "菜单"},
    {"code": "menu.weekPlan", "label": "计划 · 周计划", "group": "菜单"},
    {"code": "menu.monthPlan", "label": "计划 · 月计划", "group": "菜单"},
    {"code": "menu.positions", "label": "持仓", "group": "菜单"},
    {"code": "menu.news", "label": "股票分析 · 新闻", "group": "菜单"},
    {"code": "menu.fundamentals", "label": "股票分析 · 财报分析", "group": "菜单"},
    {"code": "menu.riskHub", "label": "风险", "group": "菜单"},
    {"code": "menu.risk", "label": "风险 · 风险模型", "group": "菜单"},
    {"code": "menu.riskPortfolios", "label": "风险 · 风险组合", "group": "菜单"},
    {"code": "menu.budgetModels", "label": "风险 · 赚亏展望", "group": "菜单"},
    {"code": "menu.kakeyaModel", "label": "风险 · 三维挂谷模型", "group": "菜单"},
    {"code": "menu.portfolio", "label": "风险 · 组合测算", "group": "菜单"},
    {"code": "menu.macro", "label": "宏观因素", "group": "菜单"},
    {"code": "menu.indicators", "label": "指标", "group": "菜单"},
    {"code": "menu.indicatorList", "label": "指标 · 指标列表", "group": "菜单"},
    {"code": "menu.indicatorVerify", "label": "指标 · 指标验证", "group": "菜单"},
    {"code": "menu.stockAnalysis", "label": "股票分析", "group": "菜单"},
    {"code": "menu.options", "label": "股票分析 · 期权分析", "group": "菜单"},
    {"code": "menu.regression", "label": "股票分析 · 股票回归线", "group": "菜单"},
    {"code": "menu.dailyWatch", "label": "股票分析 · 股票列表", "group": "菜单"},
    {"code": "menu.stockJournal", "label": "股票分析 · 股票日志", "group": "菜单"},
    {"code": "menu.fearVix", "label": "股票分析 · 恐慌指标", "group": "菜单"},
    {"code": "menu.earningsStocks", "label": "股票分析 · 财报股票", "group": "菜单"},
    {"code": "menu.stockScreener", "label": "股票分析 · 股票筛选", "group": "菜单"},
    {"code": "menu.cryptoAnalysis", "label": "虚拟币分析", "group": "菜单"},
    {"code": "menu.cryptoMarket", "label": "虚拟币 · 币列表", "group": "菜单"},
    {"code": "menu.cryptoNews", "label": "虚拟币 · 新闻", "group": "菜单"},
    {"code": "menu.cryptoStrategy", "label": "虚拟币 · 指标策略", "group": "菜单"},
    {"code": "menu.cryptoCustomStrategy", "label": "虚拟币 · 自定义策略", "group": "菜单"},
    {"code": "menu.strategy", "label": "策略", "group": "菜单"},
    {"code": "menu.pairs", "label": "策略 · 找配对", "group": "菜单"},
    {"code": "menu.intraday", "label": "策略 · 日内配对", "group": "菜单"},
    {"code": "menu.alerts", "label": "推送", "group": "菜单"},
    {"code": "menu.recipients", "label": "推送 · 推送人", "group": "菜单"},
    {"code": "menu.live", "label": "股票分析 · 实时播报", "group": "菜单"},
    {"code": "menu.users", "label": "用户管理", "group": "菜单"},
]

# 按钮 / 写操作
BUTTON_PERMS = [
    {"code": "btn.board.snap", "label": "看板 · 修改总金额", "group": "按钮"},
    {"code": "btn.board.trade", "label": "看板 · 记一笔交易", "group": "按钮"},
    {"code": "btn.board.trade_delete", "label": "看板 · 删除交易", "group": "按钮"},
    {"code": "btn.board.settings", "label": "看板 · 保存目标", "group": "按钮"},
    {"code": "btn.plans.write", "label": "计划 · 增删改", "group": "按钮"},
    {"code": "btn.crypto.write", "label": "虚拟币 · 增删改", "group": "按钮"},
    {"code": "btn.crypto.strategy", "label": "虚拟币 · 策略监听/推送", "group": "按钮"},
    {"code": "btn.positions.create", "label": "持仓 · 新增", "group": "按钮"},
    {"code": "btn.positions.edit", "label": "持仓 · 编辑", "group": "按钮"},
    {"code": "btn.positions.close", "label": "持仓 · 平仓", "group": "按钮"},
    {"code": "btn.positions.delete", "label": "持仓 · 删除", "group": "按钮"},
    {"code": "btn.alerts.write", "label": "推送 · 增删改/开关", "group": "按钮"},
    {"code": "btn.recipients.write", "label": "推送人 · 增删改/测试", "group": "按钮"},
    {"code": "btn.strategy.write", "label": "策略/套利 · 保存删除", "group": "按钮"},
    {"code": "btn.risk_portfolio.write", "label": "风险组合 · 增删改/扫描", "group": "按钮"},
    {"code": "btn.daily_watch.write", "label": "每日观察 · 增删改", "group": "按钮"},
    {"code": "btn.stock_journal.write", "label": "股票日志 · 增删改", "group": "按钮"},
    {"code": "btn.users.manage", "label": "用户 · 增删改/改总金额/改权限", "group": "按钮"},
]

ALL_PERMS = MENU_PERMS + BUTTON_PERMS
ALL_CODES = [p["code"] for p in ALL_PERMS]

# 新建普通用户默认权限（可读常用页，无写、无用户管理）
DEFAULT_USER_PERMS = [
    "menu.board",
    "menu.plans",
    "menu.dayPlan",
    "menu.weekPlan",
    "menu.monthPlan",
    "menu.positions",
    "menu.news",
    "menu.fundamentals",
    "menu.riskHub",
    "menu.risk",
    "menu.riskPortfolios",
    "menu.budgetModels",
    "menu.kakeyaModel",
    "menu.portfolio",
    "menu.macro",
    "menu.indicators",
    "menu.indicatorList",
    "menu.indicatorVerify",
    "menu.stockAnalysis",
    "menu.options",
    "menu.regression",
    "menu.dailyWatch",
    "menu.stockJournal",
    "menu.fearVix",
    "menu.earningsStocks",
    "menu.stockScreener",
    "menu.cryptoAnalysis",
    "menu.cryptoMarket",
    "menu.cryptoNews",
    "menu.cryptoStrategy",
    "menu.cryptoCustomStrategy",
    "menu.strategy",
    "menu.pairs",
    "menu.intraday",
    "menu.alerts",
    "menu.recipients",
    "menu.live",
    "btn.plans.write",
    "btn.crypto.write",
    "btn.crypto.strategy",
    "btn.stock_journal.write",
]

# view key → 需要的菜单权限
VIEW_MENU = {
    "board": "menu.board",
    "dayPlan": "menu.dayPlan",
    "weekPlan": "menu.weekPlan",
    "monthPlan": "menu.monthPlan",
    "positions": "menu.positions",
    "news": "menu.news",
    "fundamentals": "menu.fundamentals",
    "risk": "menu.risk",
    "riskPortfolios": "menu.riskPortfolios",
    "budgetModels": "menu.budgetModels",
    "kakeyaModel": "menu.kakeyaModel",
    "portfolio": "menu.portfolio",
    "macro": "menu.macro",
    "indicatorList": "menu.indicatorList",
    "indicatorVerify": "menu.indicatorVerify",
    "options": "menu.options",
    "regression": "menu.regression",
    "dailyWatch": "menu.dailyWatch",
    "dailyWatchAnalysis": "menu.dailyWatch",
    "stockJournal": "menu.stockJournal",
    "fearVix": "menu.fearVix",
    "earningsStocks": "menu.earningsStocks",
    "stockScreener": "menu.stockScreener",
    "cryptoAnalysis": "menu.cryptoMarket",
    "cryptoMarket": "menu.cryptoMarket",
    "cryptoNews": "menu.cryptoNews",
    "cryptoStrategy": "menu.cryptoStrategy",
    "cryptoStrategyBacktest": "menu.cryptoStrategy",
    "cryptoCustomStrategy": "menu.cryptoCustomStrategy",
    "cryptoCustomBacktest": "menu.cryptoCustomStrategy",
    "strategy": "menu.strategy",
    "pairs": "menu.pairs",
    "intraday": "menu.intraday",
    "alerts": "menu.alerts",
    "live": "menu.live",
    "users": "menu.users",
}


def normalize_perms(codes: list[str] | None) -> list[str]:
    if not codes:
        return []
    known = set(ALL_CODES)
    return sorted({c for c in codes if c in known})
